name: cd_flexicadastre
description: "[FlexiCadastre] DRC Mining Cadastre Portal"
schedule: weekly
pipeline:
  init:
    method: datacommons.crawlers.flexicadastre.crawler:layers
    params:
      url: http://portals.flexicadastre.com/drc/en/
      layers:
        - Zone d'Exploitation Artisanale
        - ActiveLicenses
        - Permis d''Exploitation de la Petite Mine
        - Permis d''Exploitation des Rejets
        - Autorisation de Recherches des Produits de Carrières
        - Autorisation d''Exploitation de Carrières Permanente
        - Permis d''Exploitation
        - Permis d'Exploitation
        - Permis de Recherches
        - Permis d'Exploitation de Petite Mine
        - Permis d'Exploitation des Rejets
        - Autorisation de Recherches des Produits de Carrières
        - Autorisation d'Exploitation de Carrière Permanente
    handle:
      pass: layer
  layer:
    method: datacommons.crawlers.flexicadastre.crawler:layer
    handle:
      pass: feature
  feature:
    method: datacommons.crawlers.flexicadastre.parser:feature
