name: ci_flexicadastre
description: "[FlexiCadastre] Portail du Cadastre Minier de la Côte d'Ivoire"
schedule: weekly
pipeline:
  init:
    method: datacommons.crawlers.flexicadastre.crawler:layers
    params:
      url: http://portals.flexicadastre.com/cotedivoire/
      layers:
        - PR Réservé
        - PR (Permis de Recherches)
        - AP (Autorisation de Prospection)
        - PE (Permis d'Exploitation)
        - AESI
        - AEA
        - AECA
        - AXCA
        - AECI - Concassés
        - AECI - Meubles
        - AXCI - Concassés
        - AXCI - Meubles
        - ActiveLicenses
    handle:
      pass: layer
  layer:
    method: datacommons.crawlers.flexicadastre.crawler:layer
    handle:
      pass: feature
  feature:
    method: datacommons.crawlers.flexicadastre.parser:feature
