name: ke_flexicadastre
description: "[FlexiCadastre] Kenya Mining Cadastre Portal"
schedule: weekly
pipeline:
  init:
    method: datacommons.crawlers.flexicadastre.crawler:layers
    params:
      url: https://portal.miningcadastre.go.ke/mapportal/
      # TODO: there seems to be a large amount of faulty data entry 
      # here, where license holders have been entered into the ApplNo
      # field. Maybe we need to re-map this.
      layers:
        - Mining
        - Exploration
        - Old Law Licences
        - Artisanal / Quarry
        - Applications
        - New Law Licences
    handle:
      pass: layer
  layer:
    method: datacommons.crawlers.flexicadastre.crawler:layer
    handle:
      pass: feature
  feature:
    method: datacommons.crawlers.flexicadastre.parser:feature
