name: lr_flexicadastre
description: "[FlexiCadastre] Liberia National Concession Portal"
schedule: weekly
pipeline:
  init:
    method: datacommons.crawlers.flexicadastre.crawler:layers
    params:
      url: http://portals.flexicadastre.com/liberia/
      layers:
        - Forest Management Contract
        - Timber Sale Contract
        - Agricultural Concession
        - Mineral Development Agreements
        - Oil & Gas
        - DEL
        - MEL
    handle:
      pass: layer
  layer:
    method: datacommons.crawlers.flexicadastre.crawler:layer
    handle:
      pass: feature
  feature:
    method: datacommons.crawlers.flexicadastre.parser:feature
