name: mw_flexicadastre
description: "[FlexiCadastre] Malawi Mining Cadastre Portal"
schedule: weekly
pipeline:
  init:
    method: datacommons.crawlers.flexicadastre.crawler:layers
    params:
      url: http://portals.flexicadastre.com/malawi/
      layers:
        - Petroleum Licenses
        - Mining Claims
        - Mining Licences
        - Exclusive Prospecting Licences
        - Reconnaissance Licences
        - Mining Claim
        - Mining Licence
        - Exclusive Prospecting Licence
        - Reconnaissance Licence
    handle:
      pass: layer
  layer:
    method: datacommons.crawlers.flexicadastre.crawler:layer
    handle:
      pass: feature
  feature:
    method: datacommons.crawlers.flexicadastre.parser:feature
    handle:
      commodity: commodity
      party: party
      pass: record
  record:
    method: db
    params:
      table: mw_flexicadastre
      unique: ['FeatureId']
  party:
    method: db
    params:
      table: mw_flexicadastre_party
      unique: ['FeatureId', 'Party', 'Share']
  commodity:
    method: db
    params:
      table: mw_flexicadastre_commodity
      unique: ['FeatureId', 'Commodity']
