name: na_flexicadastre
description: "[FlexiCadastre] Namibia Mining Cadastre Portal"
schedule: weekly
pipeline:
  init:
    method: datacommons.crawlers.flexicadastre.crawler:layers
    params:
      url: http://portals.flexicadastre.com/Namibia/
      layers:
        - Hydrocarbon Licences
        - Mining Licences
        - Mining Claims
        - Mineral Deposit Retention Licences
        - Exclusive Prospecting Licences
        - Reconnaissance Licences
        - Exclusive Reconnaissance Licences
        - Applications
        - ActiveLicenses
    handle:
      pass: layer
  layer:
    method: datacommons.crawlers.flexicadastre.crawler:layer
    handle:
      pass: feature
  feature:
    method: datacommons.crawlers.flexicadastre.parser:feature