name: rw_flexicadastre
description: "[FlexiCadastre] Rwanda Mining Cadastre Portal"
schedule: weekly
pipeline:
  init:
    method: datacommons.crawlers.flexicadastre.crawler:layers
    params:
      url: http://portals.flexicadastre.com/rwanda/
      layers:
        - Mining Licenses (2009)
        - Artisanal Mining Licenses
        - Small Scale Mining Licenses
        - Large Scale Mining Licenses
        - Quarry Licenses - Commercial (2009)
        - Quarry Licenses - Non Commercial (2009)
        - Large Scale Quarry Licenses
        - Small Scale Quarry Licenses - Non Commercial
        - Small Scale Quarry Licenses - Commercial
        - Prospecting Licenses
        - Exploration Licenses
        - ActiveLicenses
        - Applications
    handle:
      pass: layer
  layer:
    method: datacommons.crawlers.flexicadastre.crawler:layer
    handle:
      pass: feature
  feature:
    method: datacommons.crawlers.flexicadastre.parser:feature
    handle:
      commodity: commodity
      party: party
      pass: record
  record:
    method: db
    params:
      table: rw_flexicadastre
      unique: ['FeatureId']
  party:
    method: db
    params:
      table: rw_flexicadastre_party
      unique: ['FeatureId', 'Party', 'Share']
  commodity:
    method: db
    params:
      table: rw_flexicadastre_commodity
      unique: ['FeatureId', 'Commodity']
