name: ss_flexicadastre
description: "[FlexiCadastre] Namibia Mining Cadastre Portal"
schedule: weekly
pipeline:
  init:
    method: datacommons.crawlers.flexicadastre.crawler:layers
    params:
      url: http://portals.flexicadastre.com/southsudan/
      layers:
        - Oil Concessions
        - ' Large-Scale Mining Licenses'
        - ' Small-Scale Mining Licenses'
        - Reconnaissance Licenses
        - Exploration Licenses
        - ActiveLicenses
        - Applications
    handle:
      pass: layer
  layer:
    method: datacommons.crawlers.flexicadastre.crawler:layer
    handle:
      pass: feature
  feature:
    method: datacommons.crawlers.flexicadastre.parser:feature
